### ISSUE TITLE
Disable Adguard for "Media Storage" by default

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#1052]
The only use of "Media Storage" is loading huge media/video files. There's no need in routing it through the VPN.

Package name: `com.android.providers.media`
You'd better check its name in older Android versions, though.

**Comment by nkartyshov** [comment]
Done

**Comment by ameshkov** [comment]
I still can see traffic stats for it. Why?

**Comment by ameshkov** [comment]
I guess for it to work properly you should also disable it for shared packages:
```
Uid: 10013 shared with (com.android.providers.downloads,com.android.mtp,com.android.providers.downloads.ui)
```

**Comment by nkartyshov** [comment]
Review AJC-CR-184

**Comment by ameshkov** [comment]
Heh, I still see it. It seems, that the traffic is caused by the "MTP Host" app. I wonder, why don't I see that app in the "Apps Management" section.

**Comment by ameshkov** [comment]
Reassigned to myself.

**Comment by ameshkov** [comment]
Ok, I've done a research and now I know what is going on.

First of all, it is not "Media Storage", in fact, this is about download manager. The problem is that download manager shares UID with "Media Storage", thus it was detected instead.

Second, the only way to "fix" it is to exclude the app, that starts the download process. For instance, if we exclude "Play Store", it's downloads will no more be routed through the VPN. However, downloads started by other apps, will still be routed.

Excluding "Download Manager" and "Downloads" app does not change anything.

**Comment by ameshkov** [comment]
What I suggest:

1. Exclude "Play Store" by default (too heavy, no need to filter all those updates/downloads).
2. Change app detection algorithm, so that it was detecting "Downloads" instead of "Media Storage". At least people will understand what's that all about.

**Comment by ameshkov** [comment]
Review ID: AJC-CR-195

**Comment by Revertron** [comment]
Reverting this behavior for #3355, because our China users want to load apps through proxy.

**Comment by ichhabethe7-lang** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/1052

**Comment by ichhabethe7-lang** [comment]
YT28PA1GEBPZTSM9
