### ISSUE TITLE
Few issues with the new DNS sub-menu section

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForAndroid#1374]
I suggest to keep it as one issue.

1.  Scrollbar is missing at both DNS server lists (regular and DNScrypt)
---

2.  We should change wording a little bit @vbagirov 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/17472907/29324033-7b0a149c-81eb-11e7-862a-5e8a137a2f06.png)

</details>
<br>
"Custom DNS server" doesn't look like an option to click on, more like an info tab, let's at least name it "Choose a DNS server" or something like this
---
<br>

---

3.  Russian localization issues @zebrum 
---
4. UI glitch when 2 DNS servers are "active" @nkartyshov 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/17472907/29324399-94d5122c-81ec-11e7-9124-184ea1b96722.png)

</details>

5. In System default section text is displaced:

<details><summary>Screenshot:</summary>

![photo_2017-08-31_14-33-03](https://user-images.githubusercontent.com/23637588/29921644-0efb8598-8e5b-11e7-96f9-fcbadaf7a4a7.jpg)

</details>

**Comment by vbagirov** [comment]
@vozersky no.2 - fixed in oneskyapp.

**Comment by nkartyshov** [comment]
no.4 fixed, review AFA-CR-80

**Comment by zebrum** [comment]
added №5 
@nkartyshov please look at it

**Comment by zebrum** [comment]
And it seems that №4 is not fixed yet:
@nkartyshov 

<details>

![photo_2017-08-31_14-51-33](https://user-images.githubusercontent.com/23637588/29921842-e5dd46d2-8e5b-11e7-9323-b81b687c3b10.jpg)


</details>

**Comment by zebrum** [comment]
no.3 fixed in ru localization.

**Comment by nkartyshov** [comment]
no. 4 fixed. Can we close the issue?

**Comment by zebrum** [comment]
@nkartyshov what about №5?

**Comment by nkartyshov** [comment]
Sorry, no.5 fixed

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardForAndroid/issues/1443

**Comment by vozersky** [comment]
This issue still needs some love:

---
1.  Scrollbar is missing at both DNS server lists (regular and DNScrypt)
---

**Comment by nkartyshov** [comment]
@vozersky fixed

**Comment by vozersky** [comment]
\0/

**Comment by vozersky** [comment]
The visual glitch with 2 active DNS servers (usual one and DNSCrypt) us back

**Comment by nkartyshov** [comment]
Fixed, adguard-android/pull-requests/187

**Comment by Heresh83** [comment]
`

**Comment by Heresh83** [comment]
> ثابت ، adguard-android / pull-applications / 187
