### ISSUE TITLE
No connection when DNS is enabled

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForAndroid#3399]
- **AdGuard version:**
  -  3.3.230/3.4.60
- **Filtering mode:**
  -  VPN
- **Device:**
  -  Xiaomi Mi 9T
- **Operating system and version:**
  - 10
- **Root access:**
  -  No

The user is having a connection issues. Access to the network is blocked when protection is enabled. He reproduced the problem on the release and Nightly versions.
**Release**:
>I tried to use Opera browser at 14:15 and I tried to use Google actuality app between 14:16 and 14:17.
In both cases, I had no internet connection.

**Nightly**:
> 17:55:00 : I've enabled wifi
 17:55:35 : I've received a notification from Android services that ask to touch to connect to our wifi network
 17:55:40 : I've touched the notification
 17:55:42 : connection on the wifi network has been established

### Additional Information

HelpDesk ID: 2610666
Two archives with log files added to **NCloud**

**Comment by Chinaski1** [comment]
User reported that issue is solved.

**Comment by akmLaVx** [comment]
Same issue - seems to be unsolved - from the same user on a Huawei P20.
Look 2610666 for logs.

**Comment by lessload** [comment]
Try this
- check DNS that you use was blocked by ISP (Internet service provider) ?
- add `connect.rom.miui.com` to Whitelist. it may help. [MIUI only]

**Comment by jineshpatel30** [comment]
Internet blocking issue still present on 3.4 stable. Yes, it's less prevalent compared to 3.3 but it's definitely not fixed. 

Also, It's not actually related to switching connections between wifi/LTE because many time it blocks internet access even in same WiFi connection, it's like internet was working a minute ago now no application can connect to internet unless I go to Adguard manually, and disable protection and re-enable it. (quick setting widget turn off/on also don't work to gain internet access back)

I'm on POCO F1 but with custom ROM Android 10, so it's not like MIUI is shutting down adguard.
Plus Battery optimization is disabled
Running in Background allowed fully
Even allowed OOM adjustment via advanced setting with root

But issue stays. **(Same issue was there in stock MIUI Android 10 as well, same setup as described above)**

It's kind of random on daily basis but mostly happens after using device that has been in ideal for some time. Also, it doesn't happen right after waking up ideal device as internet works for sometime and then suddenly nothing connects ! So, manual reconnect is required to get Internet access back as described initially.

Don't know what kind of logs you'll need for this so let know.

May be below issue is linked to this issue at large so I replied to that as well.
https://github.com/AdguardTeam/AdguardForAndroid/issues/2842#issuecomment-637304567

**Comment by Chinaski1** [comment]
Looks like that user got the same issue: 2090133
Logs are added to NCloud.

**Comment by Chinaski1** [comment]
This user faced a similar issue: **801865**
- Samsung: SM-N9700 
- Android version: 9
- Logs and bug report are added to NCLoud.
- Time|Date: 23:43-23:53 | 03.06.2020

**Comment by the4anoni** [comment]
I have similar issue, galaxy s10 one ui 2.1 Q. Internet sometimes not avaible when dns filtering is turned on.

**Comment by Chinaski1** [comment]
> AdGuard does not work on mobile data with DNS filtering enabled

- DNS filtering enabled at 3:06 (No connection);
- DNS filtering disabled and  3:07 (connection stable);

HelpDesk ID: 1999050
Logs and bug report added to the NCloud.

**Comment by akmLaVx** [comment]
Similar issue has been reported by customer 2216223.

**Comment by Eugene-Savenko** [comment]
Another case here: 2844632

> Disabling the DNS filtering completely is the only solution to the problem I’ve encountered. Trying any other servers or configurations doesn’t help. The issue appears only when using mobile data, never when I’m on WiFi.

**Comment by zzebrum** [comment]
reopen if the problem still persists.

**Comment by Konfetti030** [comment]
Hello Devs,
How is it that bug is marked as fixed? In forum the DNS bug isn't also fixed.
I have a Xiaomi Mi 9 and my internet connection (WiFi and mobile data) also interrupts many times a day. Most of the time when I listen to podcasts, enabling alarm clock or switching back from airplane mode.
Any fix or workaround @Chinaski1 ?

**Comment by Chinaski1** [comment]
Hello @Konfetti030 

Does this problem recur no matter which server and what type of server is selected?
Try selecting the system one and see if the situation repeats itself.

**Comment by Konfetti030** [comment]
I don't know because I didn't play with the servers. I chose this server
and settings because the support told me as I asked for a solution to block
ads in SoundCloud app. And this was the server which fixed the problem.
I can change server but other users in this issue or your forum sad before
that the change doesn't fix it, isn't it?

Konstantin <notifications@github.com> schrieb am Mi., 17. Feb. 2021, 10:41:
