### ISSUE TITLE
Yandex Drive app does not work with HTTPS filtering

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForAndroid#387]
https://play.google.com/store/apps/details?id=ru.yandex.disk

**Comment by Bohdan-SUP** [comment]
Logs - HTL-779-36712

**Comment by ameshkov** [comment]
@Revertron we'd better find out which domain is responsible and add it to SSL whitelist.
Whitelisting the app is a bad solution as some third party apps may use Yandex Disk integration.

**Comment by Revertron** [comment]
Fixed in #388.

**Comment by ameshkov** [comment]
Issue is not fully fixed:
```
22:48:56.514 [pool-2-thread-7] WARN  com.adguard.filter.proxy.a - TCP id=100021 Error processing request http://webdav.yandex.ru:443/disk/: java.io.IOException Internal TLS error, this could be an attack
22:48:56.527 [pool-2-thread-7] WARN  com.adguard.filter.proxy.a - TCP id=100021 Error returning error response for http://webdav.yandex.ru:443/disk/:

java.io.IOException: Internal TLS error, this could be an attack
	at org.bouncycastle.crypto.tls.TlsProtocol.writeData(Unknown Source) ~[na:0.0]
	at org.bouncycastle.crypto.tls.TlsOutputStream.write(Unknown Source) ~[na:0.0]
	at java.io.OutputStream.write(OutputStream.java:82) ~[na:0.0]
	at org.apache.commons.io.IOUtils.write(Unknown Source) ~[na:0.0]
	at com.adguard.filter.b.a.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.b.i.a(Unknown Source) ~[na:0.0]
	at com.adguard.filter.b.c.b(Unknown Source) ~[na:0.0]
	at com.adguard.filter.proxy.a.a(Unknown Source) ~[na:0.0]
```

**Comment by Revertron** [comment]
We need to add two domain to ssl_whitelist:
webdav.yandex.ru
webdav.yandex.com.ua
Done.

**Comment by vgavrish** [comment]
Do not upload again video files to Yandex drive if HTTPS filtering enable

**Comment by nkartyshov** [comment]
Add domain disk.yandex.ru ro ssl_whitelist

**Comment by ameshkov** [comment]
The issue is back with the new Yandex Drive and Yandex Mail versions.

**Comment by nkartyshov** [comment]
I didn't found any problems in work with new version yandex disk and yandex mail.

@ameshkov What was the problem?

**Comment by ameshkov** [comment]
Ah, nevermind:)
