### ISSUE TITLE
The configuration file is too large to import.

### ISSUE THREAD

**Issue by honeyuee** [AdguardTeam/AdguardForAndroid#4670]
### Please answer the following questions for yourself before submitting an issue.

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard Android版 v4.0 Nightly 100

### Environment

```markdown
- OS:Android 11
- Device:Huawei
- Firmware:WLZ-AL10
```

### Root access

- [ ] Yes, I have it.

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Social Media filter, AdGuard Cookie Notices filter, AdGuard Mobile App Banners filter, EasyList China, Icelandic ABP List, Fanboy's Enhanced Tracking List, CJX's Annoyances List, Fanboy's Anti-Facebook List, xinggsf, I don't care about cookies, EasyList Cookie List, Others

### Issue Details

Steps to reproduce:
1.Open Adguard, find Settings, and then go to Import Settings in the upper right corner.
![Screenshot_20230509_105550](https://user-images.githubusercontent.com/53884928/236982776-79ac20d6-55e4-4bfd-ae8d-d64fc18ff269.jpg)

2.Go to File Management, select the configuration file you want to import, and click OK.
![Screenshot_20230509_110008](https://user-images.githubusercontent.com/53884928/236982924-e0452d2e-a13c-42e5-9c13-73ec8083830c.jpg)

3.Because this configuration file contains all of my Adguard Settings, it has a large capacity of 47.29MB.After you click Import, you will stay in the Import screen.
![Screenshot_20230509_110047](https://user-images.githubusercontent.com/53884928/236983388-dd291ee4-7d1a-4df1-8157-f242616a6d9a.jpg)

### Expected Behavior

The Adguard large configuration file cannot be imported correctly

### Actual Behavior

For the latest development version of the rule file configuration export, he can customize the content to be exported. The configuration file will be large for a user who has a good setup and needs to save the configuration. So when exporting can be fully exported, according to the import export Settings, full import should be no problem. But when I tried to do it, it didn't work.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Versty** [comment]
@honeyuee Hi! 
Please provide the configuration file and logs from your device, so we could take a look. 

1. Open AdGuard and go to **Settings** tab -> **General**.
2. Tap the **Advanced** option.
3. Set the **Logging level** to **Debug**. It's desirable to close all background apps that don't concern the problem beforehand.
4. Reproduce the issue. Notice the exact time when it happened.
6. Use the **Export logs and system info** option to save the log file to the phone storage
7. Attach the log file and configuration file to the email and send it to devteam@adguard.com, mention the issue number `#4670` in the subject and the time when the issue was reproduced.

**Comment by honeyuee** [comment]
> @honeyuee Hi! 
> Please provide the configuration file and logs from your device, so we could take a look. 
> 
> 1. Open AdGuard and go to **Settings** tab -> **General**.
> 2. Tap the **Advanced** option.
> 3. Set the **Logging level** to **Debug**. It's desirable to close all background apps that don't concern the problem beforehand.
> 4. Reproduce the issue. Notice the exact time when it happened.
> 6. Use the **Export logs and system info** option to save the log file to the phone storage
> 7. Attach the log file and configuration file to the email and send it to devteam@adguard.com, mention the issue number `#4670` in the subject and the time when the issue was reproduced.

Because I set up a new phone, there was no relevant usage record when the App failed. However, I tried importing Settings on other phones and it worked.

**Comment by Versty** [comment]
@honeyuee Do you still have the problematic settings file? If so, please send it to `devteam@adguard.com` and mention the number `4670` in the subject line. We would like to try to reproduce this issue on our side as well.

**Comment by Versty** [comment]
@honeyuee Does this issue have been resolved for you?

**Comment by honeyuee** [comment]
This problem occurred once before, I do not know whether it is a problem of the device, resulting in too long import time, and it did not recurs again. And now there's a problem with the latest Nightly version. He reboots at odd times, often.











🌤&nbsp;&nbsp;ʚ◡̈⃝ɞ日日落俗&nbsp;日日开心&nbsp;✨

---Original---
From: ***@***.***&gt;
Date: Mon, Jul 3, 2023 22:47 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [AdguardTeam/AdguardForAndroid] The configuration file is toolarge to import. (Issue #4670)




 
@honeyuee Does this issue have been resolved for you?

**Comment by Versty** [comment]
@honeyuee Does the reboot problem still exist on your device on the latest AdGuard version?

**Comment by Versty** [comment]
@honeyuee Closed due to inactivity. 
Please reopen if the problem still persists.
