### ISSUE TITLE
Downloads are broken in Android N

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForAndroid#597]
Hi! Downloading files isn't possible on Android DP3. For example, when downloading any file from APK Mirror it queues in Download Manager and never finishes. Disabling Adguard resolves the issue. Thanks!

 I have added the both
_com.android.providers.downloads_ and _com.android.providers.downloads.ui_ (the
second is useless but anyway) to the sections _pref.https.apps.exceptions_
and _pref.net.exclusions_ and even rebooted, but this doesn't solve the
issue. Any thoughts why and what else I can try?

Logs in JDN-573-45640

**Comment by ameshkov** [comment]
Is this issue specific to apkmirror?

**Comment by sviperz** [comment]
Hello!

It appears that the issue affects all downloads from any site, not only from apkmirror. Let me know if there is anything I can help you with.

Thanks!

**Comment by ameshkov** [comment]
Hi! Could you please record one more debug-level log, but this time - with com.android.providers.downloads in pref.net.exclusions?

**Comment by sviperz** [comment]
Sure! Recorded and sent (see GitHub #597 in description). I found that the both WiFi and Mobile Data networks are affected. Also, seems like the issue is showing only for HTTP URLs, while there is no any issues with HTTPS URLs downloads (checked on factory images from developers.google.com). All this cases were recorded in the log which you will receive.

**Comment by evgeniy-ADG** [comment]
@ameshkov VYQ-940-29527

**Comment by ameshkov** [comment]
@sviperz I see that HTTP requests are sent through Chrome compression proxy. I wonder is it the cause?

Could you please check the downloads without data compression?

**Comment by sviperz** [comment]
@ameshkov I was thinking that could be the reason as well (even was almost sure) and tried it with Chrome compression proxy switched off - all the same, so I didn't specify that in the report.

**Comment by sviperz** [comment]
Did you, guys, make any changes remotely? Because now everything is working as expected. No stuck downloads from any site. Oddly, Chrome now doesn't ask if I really want to download APK file as it can harm the system, all downloads start immediately no matter Adguard is off or on.

Let me know if you need logs to figure out why it is working now.

**Comment by ameshkov** [comment]
Hm, no change on our side. Maybe Chrome update? Weird.

**Comment by sviperz** [comment]
Yes, really weird. Anyway, thanks for being responsive on the issue. I'll let you know if the issue will back.

Good luck, guys!

**Comment by Revertron** [comment]
Closing for now.

**Comment by sviperz** [comment]
Hi, guys!

Unfortunately, it occurs again with absolutely the same symptoms. Chrome again have started to ask if I really want to download APK file and then downloading process is stuck in the Download Manager.

Are there any clues or observations on your side regarding this odd issue?

**Comment by ameshkov** [comment]
Hm, there is another guy on XDA with the very same issue.

One more important question: is it specific to Chrome? I mean what if you start download with some other browser? Or maybe Chrome Beta or Dev instead of the default chrome browser?

**Comment by ameshkov** [comment]
XDA link:
http://forum.xda-developers.com/showpost.php?p=67336084&postcount=1372

**Comment by sviperz** [comment]
Have tested in a bunch of browsers.

All versions of Chrome (stable, beta, dev) have the same issue.
Yandex Browser has the same issue as Chrome since it based on Chrome's codebase I guess.
Firefox (stable) has its own download manager which works as expected.
Opera (stable) has its own download manager as well and downloads files successfully.
The files downloaded from Firefox and Opera appear in standard Android Download Manager.

I wonder if there are other browsers/tools which use internal Android Download Manager for downloads we could test, but don't want to install every other browser due to the security reasons.

A guy from XDA have found his temporary solution disabling Filter Apps Traffic, which I can't test since I have no premium subscription and thus Filter Apps Traffic is always switched off for me.

Ready to help you in any ways, just let me know what else we can try.

Thanks!

**Comment by ameshkov** [comment]
@sviperz does it help to turn ad filtering off for the browser? You can do it in the firewall apps settings.

**Comment by sviperz** [comment]
Nope, doesn't help. The issue persists.

**Comment by ameshkov** [comment]
Does at least adding Chrome to pref.net.exclusions help?

**Comment by sviperz** [comment]
Yes, adding _com.android.chrome_ to **pref.net.exclusions** does help, but not a proper solution for sure.

**Comment by ameshkov** [comment]
At least we have narrowed it down to the browser app filtering.

**Comment by ameshkov** [comment]
Could you please collect "record everything" log and attach it to the issue?

**Comment by sviperz** [comment]
Yes, sure. Please find it in attachment (this is from _/sdcard/Android/data/com.adguard.android_).

**Comment by sviperz** [comment]
Wrong button in the previous comment. Here it is.
[adguard_log.zip](https://github.com/AdguardTeam/AdguardForAndroid/files/318321/adguard_log.zip)

**Comment by ameshkov** [comment]
@sviperz thanks! good news from our side: I am on DP4 now too and now I can reproduce the very same issue:)

**Comment by sviperz** [comment]
Great! Hope you'll find a solution. Let me know if I can help in further testing.

**Comment by Bohdan-SUP** [comment]
User 1317589 can't download attachments in Inbox on DP4.
Disabling ad filtering in Firewall - no joy.
Adding com.google.android.apps.inbox to pref.net.exclusions helped.

**Comment by sviperz** [comment]
Version _2.7.153 Beta_ is out today, but the issue is still there, though some **Android N** fixes are mentioned in the changelog. Is this bug permanent now? Are you guys working on a solution?

**Comment by ameshkov** [comment]
> Version 2.7.153 Beta is out today, but the issue is still there, though some Android N fixes are mentioned in the changelog. Is this bug permanent now? Are you guys working on a solution?

Yeah, the issue is still here. In fact I have found the cause, just forgot to mention it here.

It seems that this is a known issue of Android N, here is an open bug in their bugtracker:
https://code.google.com/p/android/issues/detail?id=33666

Temporary solutions:
1. Turn "Filter DNS requests" on in AG advanced settings.
2. Override system DNS in AG low-level settings: go to settings-advanced-low level, open "pref.vpn.dns" and set something there (for instance, you can use google dns 8.8.8.8 and 8.8.4.4)

**Comment by ameshkov** [comment]
More than this, the issue seems to be very old and affecting all android versions. However, only in Nougat I can easily reproduce this issue while in older Android versions i've never been able to do it.

**Comment by ameshkov** [comment]
@TPS could you please take a look? Seems to be the same issue as #186

**Comment by sviperz** [comment]
> 1. Turn "Filter DNS requests" on in AG advanced settings.

Since it's a premium subscription feature no go for me. Though seems like using **pref.vpn.dns** is just enough to make it work so far. Finally!

Anyway, AG is crashing several times in an hour and stops to operate after every crash. This is hardly related to this particular issue, so just letting you know.

Thanks for solution!

**Comment by ameshkov** [comment]
> Anyway, AG is crashing several times in an hour and stops to operate after every crash. This is hardly related to this particular issue, so just letting you know.

Even in v2.7? I am just using it with Nougat and never experienced any crashes. Could you please report these crashes to support and post here your customer ID after that? I'd like to take a look at the logs.

Regarding the premium features, you could apply for the beta testing program and get a license key:
https://forum.adguard.com/index.php?threads/adguard-for-android-beta-test.1707/

**Comment by sviperz** [comment]
> Even in v2.7?

Yes. But hard to reproduce. Sometimes it crashes several time per hour, sometimes no crashes at all. At least I can send a screenshot with FC window, though it won't help.

> Could you please report these crashes to support and post here your customer ID after that?

How can I do it? As always via Send Feedback in the app? And what is that customer ID and where can I check it? Is there any way to obtain necessary logs without being permanently in Record everything logging level?

P. S. Tanks for legal way to get a license key!

**Comment by ameshkov** [comment]
> How can I do it? As always via Send Feedback in the app? And what is that customer ID and where can I check it? Is there any way to obtain necessary logs without being permanently in Record everything logging level?

Yep, just send it via send feedback. You should receive the customer ID in the very first autoreply email (we have recently changed the support system, so it is now customer ID instead of the ticket ID).

**Comment by sviperz** [comment]
Alright, got it! I will report if it will be possible to reproduce or at least observe the crashes. For now I'm on Nougat DP5 since yesterday and no crashes so far.

**Comment by sviperz** [comment]
Hi, guys! Just wanted to let you know there is not a single issue since Nougat DP5 update. No crashes, no odd behavior while downloading files or any other issues. Well done!

**Comment by ameshkov** [comment]
@sviperz even without DNS filtering?

**Comment by sviperz** [comment]
@ameshkov yes, exactly. _Filter DNS requests_ option is disabled in my case. Just have **8.8.8.8** and **8.8.4.4** in _pref.vpn.dns_ in _Low Level Settings_ and that's all. Even constantly appeared crashes mentioned previously are not the thing for now (since Nougat DP5).

**Comment by ameshkov** [comment]
> Just have 8.8.8.8 and 8.8.4.4 in pref.vpn.dns in Low Level Settings and that's all

Why, it could also fix the issue. What if you do not change the DNS settings?

**Comment by sviperz** [comment]
Well, seems like I misread possible solution(S) in your comment https://github.com/AdguardTeam/AdguardForAndroid/issues/597#issuecomment-233296349

I thought this should be used combined, but those are two independent solutions.

But now, wow, it works without using any of those solutions! Does it mean the antient android bug is fixed in DP5? Finger crossed it will persist in future OS updates.

**Comment by ameshkov** [comment]
> But now, wow, it works without using any of those solutions! Does it mean the antient android bug is fixed in DP5? Finger crossed it will persist in future OS updates.

I am pretty sure that bug is not fixed, maybe it has returned to the "random" state as it was before:)

**Comment by ameshkov** [comment]
One more bug that could potentially cause the issue:
https://code.google.com/p/android/issues/detail?id=213341

**Comment by TPS** [comment]
I'm running 7/Nougat now, so if you need testing/data/whatever, count me in. ☺️
However, this (currently? 😜) WFM.... 🤷

**Comment by evgeniy-ADG** [comment]
Reopening the task as I was told here: 1273363 (Jan 23)

WE have the next problem:

> When i have DNS block enabled including low level settings from your
> guide on how to block ads with lowest battery consumption Google play
> app is not downloading updates or apps at all. please advise.

What as done but didn't help:

Open Adguard, navigate to settings -> advanced -> low-level
Find pref.vpn.dns and tap on it
Enter google dns address there: 8.8.8.8
Restart AG

In a regular mode works fine, please assist, see logs in the same ticket (Jan 23).

**Comment by ameshkov** [comment]
@evgeniy-ADG yeah, this is a known Android bug (it was linked in some comment above).

The problem is that it's rather random, I can't reproduce it on my device.

**Comment by bendingtime** [comment]
> @evgeniy-ADG yeah, this is a known Android bug (it was linked in some comment above).
The problem is that it's rather random, I can't reproduce it on my device.
Fair enough. Find someone with OP3T with Adguard "battery saver mode" enabled but it does not solve the issue. Issue You are referring too is connected with VPN. When VPN was enabled no download was possible.

**Comment by ameshkov** [comment]
@bendingtime why? It is directly caused by the VPN API:
https://code.google.com/p/android/issues/detail?id=213341

The problem is that `DownloadManager` might be broken in the case of a VPN app changing system DNS settings. However, the bug is not stable, and Google still cannot answer what's the cause of it.

**Comment by bendingtime** [comment]
Because when I use Opera VPN i have no problems with downloads whatsoever. I believe that we may narrow down the case a bit more. Don't you think?

**Comment by ameshkov** [comment]
@bendingtime it means that Opera VPN does not change DNS settings using the VPN API.

That's why AG does not change it as well unless you explicitly opt to do it.

**Comment by bendingtime** [comment]
@ameshkov If both apps does not change the DNS, both are treated as a VPN on OS and only one does not allow to download maybe it is not connected to Android N issue?

**Comment by ameshkov** [comment]
@bendingtime, got it. Let me, please explain it then (I guess I should have done it earlier, sorry).

Quoting ticket:
> When i have DNS block enabled including low level settings from your

As I understand, you've enabled "Filtering DNS requests" feature.

Here's what's done by AG in this case:
1. It uses VPN API to change system DNS to some fake IP address (80.80.80.80).
2. AG intercepts requests to these fake IP addresses and check if a host is blocked or not.
3. If the host is not blocked, we redirect request back to the real DNS server.

So, this feature causes changing the DNS settings. 

However, I suppose we can avoid this by not involving fake IPs, I've just filed a change request:
https://github.com/AdguardTeam/AdguardForAndroid/issues/1038

**Comment by bendingtime** [comment]
@ameshkov now I get it perfectly. Thank you. I can participate in beta if you are willing to test that solution.

**Comment by ameshkov** [comment]
@bendingtime thank you! I left a reminder in that new task: https://github.com/AdguardTeam/AdguardForAndroid/issues/1038#issuecomment-276701470

Regarding the beta test, you can simply switch update channel in Adguard settings. Or you can become Adguard's beta tester officially: https://blog.adguard.com/en/adguard-beta-test/

**Comment by bendingtime** [comment]
@ameshkov I am on the beta version since the day I have installed the app ;)

**Comment by Revertron** [comment]
We are trying hard to make our betas as stable as releases ;-)

**Comment by ameshkov** [comment]
This issue is now labeled as "Android Bug".

Related bugs:
https://code.google.com/p/android/issues/detail?id=213341
https://code.google.com/p/android/issues/detail?id=33666

**Comment by TPS** [comment]
Just FYI: I _almost_ never have this bug anymore.  The _only_ time I remember is whenever I've an OTA ROM update for my phone, which, since I'm w/ the ß-test group _(also 😉)_, I get about 1× monthly, but most other folks, probably max 3× over the entire life of their device.
